export interface MatchPair {
  id: number
  term: string
  concept: string
  category: string
  difficulty: "سهل" | "متوسط" | "صعب"
  description: string
}

export const allMatchPairs: MatchPair[] = [
  // البرمجة وتطوير الويب (20 زوج)
  {
    id: 1,
    term: "HTML",
    concept: "هيكل صفحات الويب",
    category: "تطوير الويب",
    difficulty: "سهل",
    description: "لغة ترميز النص التشعبي",
  },
  {
    id: 2,
    term: "CSS",
    concept: "تنسيق وتصميم الصفحات",
    category: "تطوير الويب",
    difficulty: "سهل",
    description: "أوراق الأنماط المتتالية",
  },
  {
    id: 3,
    term: "JavaScript",
    concept: "التفاعل والديناميكية",
    category: "تطوير الويب",
    difficulty: "متوسط",
    description: "لغة برمجة للويب",
  },
  {
    id: 4,
    term: "React",
    concept: "مكتبة واجهات المستخدم",
    category: "تطوير الويب",
    difficulty: "متوسط",
    description: "إطار عمل JavaScript",
  },
  {
    id: 5,
    term: "Node.js",
    concept: "تشغيل JavaScript على الخادم",
    category: "تطوير الويب",
    difficulty: "متوسط",
    description: "بيئة تشغيل JavaScript",
  },
  {
    id: 6,
    term: "Python",
    concept: "لغة برمجة متعددة الاستخدامات",
    category: "البرمجة",
    difficulty: "سهل",
    description: "لغة برمجة عالية المستوى",
  },
  {
    id: 7,
    term: "Java",
    concept: "اكتب مرة، شغل في أي مكان",
    category: "البرمجة",
    difficulty: "متوسط",
    description: "لغة برمجة كائنية التوجه",
  },
  {
    id: 8,
    term: "SQL",
    concept: "استعلام قواعد البيانات",
    category: "قواعد البيانات",
    difficulty: "متوسط",
    description: "لغة الاستعلام المهيكلة",
  },
  {
    id: 9,
    term: "Git",
    concept: "التحكم في إصدارات الكود",
    category: "أدوات التطوير",
    difficulty: "متوسط",
    description: "نظام التحكم في الإصدارات",
  },
  {
    id: 10,
    term: "API",
    concept: "واجهة تطبيق البرمجة",
    category: "التكامل",
    difficulty: "متوسط",
    description: "ربط التطبيقات ببعضها",
  },
  {
    id: 11,
    term: "JSON",
    concept: "تنسيق تبادل البيانات",
    category: "البيانات",
    difficulty: "سهل",
    description: "كائن JavaScript المُرمز",
  },
  {
    id: 12,
    term: "MongoDB",
    concept: "قاعدة بيانات غير علائقية",
    category: "قواعد البيانات",
    difficulty: "متوسط",
    description: "قاعدة بيانات NoSQL",
  },
  {
    id: 13,
    term: "Docker",
    concept: "حاويات التطبيقات",
    category: "أدوات التطوير",
    difficulty: "صعب",
    description: "منصة الحاويات",
  },
  {
    id: 14,
    term: "Bootstrap",
    concept: "إطار عمل CSS جاهز",
    category: "تطوير الويب",
    difficulty: "سهل",
    description: "مكتبة تصميم سريعة الاستجابة",
  },
  {
    id: 15,
    term: "Vue.js",
    concept: "إطار عمل JavaScript تدريجي",
    category: "تطوير الويب",
    difficulty: "متوسط",
    description: "إطار عمل واجهات المستخدم",
  },
  {
    id: 16,
    term: "TypeScript",
    concept: "JavaScript مع الأنواع",
    category: "البرمجة",
    difficulty: "متوسط",
    description: "لغة برمجة مطورة من JavaScript",
  },
  {
    id: 17,
    term: "REST API",
    concept: "واجهة برمجية تمثيلية للحالة",
    category: "التكامل",
    difficulty: "متوسط",
    description: "معيار لبناء واجهات API",
  },
  {
    id: 18,
    term: "GraphQL",
    concept: "لغة استعلام للواجهات البرمجية",
    category: "التكامل",
    difficulty: "صعب",
    description: "بديل مرن لـ REST API",
  },
  {
    id: 19,
    term: "Webpack",
    concept: "حزم وبناء التطبيقات",
    category: "أدوات التطوير",
    difficulty: "صعب",
    description: "أداة لتجميع ملفات JavaScript",
  },
  {
    id: 20,
    term: "Redux",
    concept: "إدارة حالة التطبيق",
    category: "تطوير الويب",
    difficulty: "صعب",
    description: "مكتبة لإدارة الحالة في React",
  },

  // قواعد البيانات والتخزين (10 أزواج)
  {
    id: 21,
    term: "PostgreSQL",
    concept: "قاعدة بيانات علائقية متقدمة",
    category: "قواعد البيانات",
    difficulty: "صعب",
    description: "قاعدة بيانات مفتوحة المصدر",
  },
  {
    id: 22,
    term: "Firebase",
    concept: "منصة تطوير للويب والجوال",
    category: "قواعد البيانات",
    difficulty: "متوسط",
    description: "منصة Google السحابية",
  },
  {
    id: 23,
    term: "Redis",
    concept: "تخزين البيانات في الذاكرة",
    category: "قواعد البيانات",
    difficulty: "صعب",
    description: "قاعدة بيانات مفتوحة المصدر سريعة",
  },
  {
    id: 24,
    term: "ORM",
    concept: "تعيين الكائنات العلائقية",
    category: "قواعد البيانات",
    difficulty: "متوسط",
    description: "تقنية لربط البرمجة بقواعد البيانات",
  },
  {
    id: 25,
    term: "MySQL",
    concept: "نظام إدارة قواعد البيانات",
    category: "قواعد البيانات",
    difficulty: "متوسط",
    description: "قاعدة بيانات علائقية شائعة",
  },
  {
    id: 26,
    term: "Elasticsearch",
    concept: "محرك بحث وتحليل",
    category: "قواعد البيانات",
    difficulty: "صعب",
    description: "بحث نصي كامل وتحليلات",
  },
  {
    id: 27,
    term: "Cassandra",
    concept: "قاعدة بيانات موزعة عالية الأداء",
    category: "قواعد البيانات",
    difficulty: "صعب",
    description: "قاعدة بيانات عمودية موزعة",
  },
  {
    id: 28,
    term: "AWS S3",
    concept: "تخزين الكائنات السحابي",
    category: "التخزين",
    difficulty: "متوسط",
    description: "خدمة تخزين من Amazon",
  },
  {
    id: 29,
    term: "Blockchain",
    concept: "سلسلة كتل لا مركزية",
    category: "التخزين",
    difficulty: "صعب",
    description: "تقنية دفتر الأستاذ الموزع",
  },
  {
    id: 30,
    term: "CDN",
    concept: "شبكة توزيع المحتوى",
    category: "التخزين",
    difficulty: "متوسط",
    description: "تسريع تسليم محتوى الويب",
  },

  // الشبكات والأمان (10 أزواج)
  {
    id: 31,
    term: "HTTPS",
    concept: "بروتوكول نقل النص التشعبي الآمن",
    category: "الشبكات",
    difficulty: "سهل",
    description: "بروتوكول آمن لنقل البيانات على الويب",
  },
  {
    id: 32,
    term: "SSH",
    concept: "قشرة آمنة",
    category: "الشبكات",
    difficulty: "متوسط",
    description: "بروتوكول للوصول الآمن للخوادم",
  },
  {
    id: 33,
    term: "VPN",
    concept: "شبكة خاصة افتراضية",
    category: "الشبكات",
    difficulty: "متوسط",
    description: "اتصال آمن عبر شبكة عامة",
  },
  {
    id: 34,
    term: "Firewall",
    concept: "جدار الحماية",
    category: "الأمان",
    difficulty: "متوسط",
    description: "حماية من الوصول غير المصرح به",
  },
  {
    id: 35,
    term: "JWT",
    concept: "رمز ويب JSON",
    category: "الأمان",
    difficulty: "متوسط",
    description: "معيار مفتوح للمصادقة",
  },
  {
    id: 36,
    term: "OAuth",
    concept: "معيار مفتوح للتفويض",
    category: "الأمان",
    difficulty: "متوسط",
    description: "بروتوكول تفويض آمن",
  },
  {
    id: 37,
    term: "CORS",
    concept: "مشاركة موارد عبر المنشأ",
    category: "الشبكات",
    difficulty: "متوسط",
    description: "آلية أمان للمتصفح",
  },
  {
    id: 38,
    term: "DDoS",
    concept: "هجوم حرمان الخدمة الموزع",
    category: "الأمان",
    difficulty: "صعب",
    description: "هجوم يستهدف توافر الخدمة",
  },
  {
    id: 39,
    term: "XSS",
    concept: "برمجة نصية عبر المواقع",
    category: "الأمان",
    difficulty: "صعب",
    description: "ثغرة أمنية في تطبيقات الويب",
  },
  {
    id: 40,
    term: "SSL/TLS",
    concept: "طبقة المقابس الآمنة/أمان طبقة النقل",
    category: "الأمان",
    difficulty: "صعب",
    description: "بروتوكولات تشفير للاتصالات",
  },

  // البنية التحتية والتشغيل (10 أزواج)
  {
    id: 41,
    term: "CI/CD",
    concept: "التكامل المستمر/التسليم المستمر",
    category: "التشغيل",
    difficulty: "صعب",
    description: "ممارسات أتمتة تطوير البرمجيات",
  },
  {
    id: 42,
    term: "Kubernetes",
    concept: "إدارة الحاويات المتناسقة",
    category: "البنية التحتية",
    difficulty: "صعب",
    description: "منصة أوركسترا للحاويات",
  },
  {
    id: 43,
    term: "Terraform",
    concept: "البنية التحتية كرمز",
    category: "البنية التحتية",
    difficulty: "صعب",
    description: "أداة للبنية التحتية القابلة للبرمجة",
  },
  {
    id: 44,
    term: "Serverless",
    concept: "الحوسبة بدون خادم",
    category: "البنية التحتية",
    difficulty: "متوسط",
    description: "نموذج تشغيل سحابي",
  },
  {
    id: 45,
    term: "Load Balancer",
    concept: "موازن التحميل",
    category: "البنية التحتية",
    difficulty: "متوسط",
    description: "توزيع حركة المرور على الخوادم",
  },
  {
    id: 46,
    term: "Microservices",
    concept: "الخدمات المصغرة",
    category: "البنية التحتية",
    difficulty: "صعب",
    description: "هيكلية برمجية موزعة",
  },
  {
    id: 47,
    term: "Caching",
    concept: "التخزين المؤقت",
    category: "التشغيل",
    difficulty: "متوسط",
    description: "تخزين البيانات للوصول السريع",
  },
  {
    id: 48,
    term: "Auto-scaling",
    concept: "التوسع التلقائي",
    category: "التشغيل",
    difficulty: "صعب",
    description: "ضبط الموارد حسب الطلب",
  },
  {
    id: 49,
    term: "Containerization",
    concept: "الحوسبة المعزولة",
    category: "البنية التحتية",
    difficulty: "متوسط",
    description: "تعبئة البرامج ومكوناتها",
  },
  {
    id: 50,
    term: "Nginx",
    concept: "خادم ويب عكسي",
    category: "البنية التحتية",
    difficulty: "متوسط",
    description: "خادم ويب وبروكسي عكسي",
  },

  // الذكاء الاصطناعي وعلم البيانات (10 أزواج)
  {
    id: 51,
    term: "Machine Learning",
    concept: "تعلم الآلة",
    category: "الذكاء الاصطناعي",
    difficulty: "صعب",
    description: "خوارزميات تتعلم من البيانات",
  },
  {
    id: 52,
    term: "Neural Networks",
    concept: "الشبكات العصبية",
    category: "الذكاء الاصطناعي",
    difficulty: "صعب",
    description: "نماذج محاكاة للدماغ البشري",
  },
  {
    id: 53,
    term: "NLP",
    concept: "معالجة اللغة الطبيعية",
    category: "الذكاء الاصطناعي",
    difficulty: "صعب",
    description: "تفاعل الآلات مع اللغة البشرية",
  },
  {
    id: 54,
    term: "Computer Vision",
    concept: "رؤية الحاسوب",
    category: "الذكاء الاصطناعي",
    difficulty: "صعب",
    description: "تمكين الآلات من فهم الصور",
  },
  {
    id: 55,
    term: "Big Data",
    concept: "البيانات الضخمة",
    category: "علم البيانات",
    difficulty: "متوسط",
    description: "مجموعات بيانات كبيرة ومعقدة",
  },
  {
    id: 56,
    term: "Data Mining",
    concept: "التنقيب عن البيانات",
    category: "علم البيانات",
    difficulty: "صعب",
    description: "استخراج المعرفة من البيانات",
  },
  {
    id: 57,
    term: "TensorFlow",
    concept: "مكتبة للتعلم الآلي",
    category: "الذكاء الاصطناعي",
    difficulty: "صعب",
    description: "منصة برمجية للتعلم الآلي",
  },
  {
    id: 58,
    term: "Data Visualization",
    concept: "تصوير البيانات",
    category: "علم البيانات",
    difficulty: "متوسط",
    description: "عرض البيانات بشكل مرئي",
  },
  {
    id: 59,
    term: "Predictive Analytics",
    concept: "التحليلات التنبؤية",
    category: "علم البيانات",
    difficulty: "صعب",
    description: "التنبؤ بالأحداث المستقبلية",
  },
  {
    id: 60,
    term: "Reinforcement Learning",
    concept: "التعلم المعزز",
    category: "الذكاء الاصطناعي",
    difficulty: "صعب",
    description: "نهج في التعلم الآلي يعتمد على المكافأة",
  },
]
